version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bankir
      POSTGRES_PASSWORD: bank123
    ports:
      - "5433:5432"